/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem/index.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton/index.vue')['default']
    CustomDivider: typeof import('./src/components/CustomDivider/index.vue')['default']
    CustomEditor: typeof import('./src/components/CustomEditor/index.vue')['default']
    CustomElImage: typeof import('./src/components/CustomElImage/index.vue')['default']
    CustomEmpty: typeof import('./src/components/CustomEmpty/index.vue')['default']
    CustomUploadAvatar: typeof import('./src/components/CustomUploadAvatar/index.vue')['default']
    DocMenu: typeof import('./src/components/TopNavBar/components/DocMenu.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FooterItem: typeof import('./src/components/FooterItem/index.vue')['default']
    Logo: typeof import('./src/components/TopNavBar/components/Logo.vue')['default']
    MyCursor: typeof import('./src/components/MyCursor/index.vue')['default']
    MyPageHeader: typeof import('./src/components/MyPageHeader/index.vue')['default']
    Pollup: typeof import('./src/components/TopNavBar/components/Pollup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagChoose: typeof import('./src/components/TagChoose/index.vue')['default']
    TagItem: typeof import('./src/components/TagItem/index.vue')['default']
    Tools: typeof import('./src/components/TopNavBar/components/Tools.vue')['default']
    TopNavBar: typeof import('./src/components/TopNavBar/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
