name: CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # 任务ID
  build-front:
    # 运行环境
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.10.0 ]
    # 步骤
    steps:
      - uses: actions/checkout@v3
      # 安装 node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # 安装依赖
      - name: 安装依赖
        run: npm cache clean -f && npm install -f
        working-directory: ./goffee-front
      # 打包
      - name: 打包
        run: npm run build --if-present
        working-directory: ./goffee-front
      # 上传至阿里服务器
      - name: 部署
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.ALI_PRIVATE_KEY }}
          # scp 参数
          ARGS: '-avzr --delete'
          # 服务器地址
          REMOTE_HOST: ${{ secrets.USER_HOST }}
          # 用户名
          REMOTE_USER: ${{ secrets.USER }}
          # 源目录
          SOURCE: './goffee-front/dist'
          # 目标目录
          TARGET: ${{ secrets.USER_FRONT_PATH }}
  build-backstage:
    # 运行环境
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.10.0 ]
    # 步骤
    steps:
      - uses: actions/checkout@v3
      # 安装 node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # 安装依赖
      - name: 安装依赖
        working-directory: ./goffee-backstage
        run: npm cache clean -f && npm install -f
      # 打包
      - name: 打包
        working-directory: ./goffee-backstage
        run: npm run build --if-present
      # 上传至阿里服务器
      - name: 部署
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.ALI_PRIVATE_KEY }}
          # scp 参数
          ARGS: '-avzr --delete'
          # 服务器地址
          REMOTE_HOST: ${{ secrets.USER_HOST }}
          # 用户名
          REMOTE_USER: ${{ secrets.USER }}
          # 源目录
          SOURCE: './goffee-backstage/dist'
          # 目标目录
          TARGET: ${{ secrets.USER_BACKSTAGE_PATH }}